### PR TITLE
some fixes

### LINKED ISSUE #30: Links look "boxy" on Safari desktop
Looks good on Chrome, Firefox and Safari on iphone.
So seems specific to Safari on Desktop. I'm using Safari v15.1 on MacOS 12.01

Screen Shot 2022-10-19 at 9 44 23 AM

### PR DESCRIPTION
**Pull request by rolandpo**
- fix https://github.com/OriginProtocol/website-frontend/issues/30
- remove header background color on hover
- add active header element indicator on ousd

### CODE REVIEW

File: src/components/Button/index.tsx [hunk 1]
```diff
@@ -125,7 +125,7 @@ export const Button = ({
   let padding;
   switch (size) {
     case "nav":
-      textSize = "text-base font-medium";
+      textSize = "text-base font-normal";
```
Comment (nickick) [inline src/components/Button/index.tsx:133]: this needs to be `font-medium` for story.xyz designs.  if you use `size="small"` for OUSD / website I think that would work?

File: src/components/Button/index.tsx [hunk 2]
```diff
@@ -82,11 +82,11 @@ export const Button = ({
         type === "primary"
           ? "bg-gradient-to-r from-origin-protocol-button-start to-origin-protocol-button-end"
           : "bg-transparent";
-      textColor = type === "primary" ? "text-white" : "text-black";
+      textColor = type === "primary" ? "text-white" : "text-slate-800";
```
Comment (nickick) [inline src/components/Button/index.tsx]: this would default all button styles to slate-800, is that what we want?

File: src/components/Header/index.tsx [hunk 3]
```diff
@@ -35,9 +35,11 @@ export type IconFormatted = {
 const NavLinks = ({
   mappedLinks,
   webProperty,
+  active,
 }: {
   mappedLinks: MappedLink<LinkFormatted<IconFormatted>>[];
   webProperty: "originprotocol" | "ousd" | "story";
+  active: string;
```
Comment (nickick) [inline src/components/Header/index.tsx]: where is active being set? is this data we're getting from the CMS?

**Review by nickick — COMMENTED** [review]
I've got some comments that would be good to address.

File: src/components/Button/index.tsx (hunk 1 above)
Comment (rolandpo) [reply src/components/Button/index.tsx:133]: i think all sites use a font weight 400, no?

File: src/components/Button/index.tsx (hunk 2 above)
Comment (rolandpo) [reply src/components/Button/index.tsx]: is it necessary to use button in the header then, if it's just a link with no styling?

File: src/components/Header/index.tsx (hunk 3 above)
Comment (rolandpo) [reply src/components/Header/index.tsx]: it would just be passed in directly on the website, just like webProperty

File: src/components/Button/index.tsx (hunk 1 above)
Comment (nickick) [reply src/components/Button/index.tsx:133]: oh wait yeah I'm seeing that in the story design now.

File: src/components/Header/index.tsx (hunk 3 above)
Comment (nickick) [reply src/components/Header/index.tsx]: okay gotcha - let's also add a comment on what's meant by active in the props

File: src/components/Button/index.tsx (hunk 2 above)
Comment (nickick) [reply src/components/Button/index.tsx]: we want some sort of hover indicator, and usually if there are dropdowns and buttons around a link it makes sense I think to keep it as a button with the additional padding for hover / click targets.

Comment (nickick) [reply src/components/Button/index.tsx]: Also there are definitely buttons on the story.xyz and op.com designs that use #000000 for button text, so this isn't the right way to do this. Maybe another ternary here that looks for the ousd webProperty if you need it?

**Review by nickick — APPROVED** [review]
LGTM, thanks for responding to comments
